# settings and data for the generator
name: 'Girotondo e.V.'
country: 'DE'
update_delay: 0
overtime_factor: 1.5
subdiv: 'BY'
year: 2022
language: 'DE'
weekend: 'Wochenende'
holiday: 'Feiertag'
# format is used for all dates
format: '%d/%m'
styles:
  - '20 % - Accent6'
  - '20 % - Accent2'
  - '20 % - Accent1'
  - '40 % - Accent3'
  - 'Output'
# dates have to be in the format defined in the global section
holidays:
  - name: 'Weihnachtsferien'
    dates:
      - '03/01'
      - '04/01'
      - '05/01'
      - '07/01'
      - '27/12'
      - '28/12'
      - '29/12'
      - '30/12'
  - name: 'Brückentag'
    dates:
      - '27/05'
      - '17/06'
  - name: 'Sommerferien'
    dates:
      - '16/08'
      - '17/08'
      - '18/08'
      - '19/08'
  - name: 'Pädagogischer Tag'
    dates:
      - '06/05'
      - '26/09'
members:
  - name: 'Mustermann'
    hours: [ 8,8,8,8,7 ]
